name: snowflake_dbt_mini_project
version: 1.0.0
config-version: 2

profile: snowflake_dbt_mini_project

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  snowflake_dbt_mini_project:
    staging:
      +materialized: view
      +schema: staging
      +tags:
        - staging