-- ============================================================
-- File: load_raw_applications.sql
-- Purpose: Load applications JSON into RAW_APPLICATIONS
-- ============================================================

USE ROLE DBT_ROLE;
USE WAREHOUSE DBT_WH;
USE DATABASE DBT_MINI_PROJECT;
USE SCHEMA RAW;

-- Preview source
SELECT
    t.$1 AS RAW_RECORD,
    METADATA$FILENAME AS FILE_NAME,
    METADATA$FILE_ROW_NUMBER AS FILE_ROW_NUMBER
FROM @DBT_MINI_PROJECT.DBT_MINI_DEV.S3_DBT_MINI_STAGE/applications/
(
    FILE_FORMAT =>
      DBT_MINI_PROJECT.DBT_MINI_DEV.JSON_FILE_FORMAT
) t
LIMIT 10;

-- Load source
COPY INTO DBT_MINI_PROJECT.RAW.RAW_APPLICATIONS
(
    INGESTION_RECORD_ID,
    ENTITY_NAME,
    RAW_RECORD,
    SOURCE_SYSTEM,
    SOURCE_OBJECT,
    FILE_TYPE,
    FILE_NAME,
    FILE_ROW_NUMBER,
    FILE_CONTENT_KEY,
    FILE_LAST_MODIFIED,
    SCAN_START_TIME,
    LOAD_TIMESTAMP,
    BATCH_ID,
    RUN_MODE,
    CONTRACT_VERSION,
    SOURCE_DATE,
    BACKFILL_FROM_DATE,
    BACKFILL_TO_DATE
)
FROM
(
    SELECT
        UUID_STRING(),
        'APPLICATIONS',
        t.$1,
        'AWS_S3',
        'APPLICATIONS',
        'JSON',

        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER,
        METADATA$FILE_CONTENT_KEY,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$START_SCAN_TIME,
        METADATA$START_SCAN_TIME,

        'HIST_20260830_002',
        'BACKFILL',
        '1.0',

        TO_DATE(METADATA$FILE_LAST_MODIFIED),
        NULL::DATE,
        NULL::DATE

    FROM @DBT_MINI_PROJECT.DBT_MINI_DEV.S3_DBT_MINI_STAGE/applications/
    (
        FILE_FORMAT =>
          DBT_MINI_PROJECT.DBT_MINI_DEV.JSON_FILE_FORMAT
    ) t
)
ON_ERROR = 'ABORT_STATEMENT';


-- Generate record hashes
UPDATE DBT_MINI_PROJECT.RAW.RAW_APPLICATIONS
SET RECORD_HASH = SHA2(TO_JSON(RAW_RECORD), 256)
WHERE BATCH_ID = 'HIST_20260830_002'
  AND RECORD_HASH IS NULL;